services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    expose:
      - 5432
  
  server:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
    - db

    ports:
    - ${PORT}:${PORT}